# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 03c81a256862e5f3b9c496a32c6aeb50985db88e353e26ed6d66bf59087edec6a02f4a603f7d036531177dc266edd59b54908a0dbaebab263143e41a1e51f325

test:
  secret_key_base: 7914f904a2349a87bb632bd01b2f005ee96cff1c3af48adcb003d3a5172ec3634f496d065dc8598dbcb686e5c78247510130edb714d4751c60f8a9455e455822

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
